package types

const (
	// RACE TYPE
	RACE_CONVENTIONAL = "CONVENTIONAL"
	RACE_TIME_TRIAL   = "TIME_TRIAL"

	// MODALITIES
	RACE_TRAINERA    = "TRAINERA"
	RACE_TRAINERILLA = "TRAINERILLA"
	RACE_BATEL       = "BATEL"

	// CATEGORIES
	CATEGORY_ALL     = "ALL"
	CATEGORY_ABSOLUT = "ABSOLUT"
	CATEGORY_VETERAN = "VETERAN"
	CATEGORY_SCHOOL  = "SCHOOL"

	// ENTITIES
	ENTITY_CLUB       = "CLUB"
	ENTITY_LEAGUE     = "LEAGUE"
	ENTITY_FEDERATION = "FEDERATION"
	ENTITY_PRIVATE    = "PRIVATE"

	// GENDERS
	GENDER_ALL    = "ALL"
	GENDER_MALE   = "MALE"
	GENDER_FEMALE = "FEMALE"
	GENDER_MIX    = "MIX"
)
